type Product {
  _id: ID
  title: String!
  imageUrl: String!
  description: String!
  categories: [String]!
  createdDate: String
  likes: Int
}

type User {
  _id: ID
  username: String! @unique
  password: String!
  email: String!
  joinDate: String
  # favorites: [Recipe]
}

type Token {
  token: String!
}

type Query {
  getAllProducts: [Product]!
}

type Mutation {
  addProduct(
    title: String!
    imageUrl: String!
    description: String!
    categories: [String]!
  ): Product!
  signinUser(username: String!, password: String!): Token
  signupUser(username: String!, email: String!, password: String!): Token
}
