type Product {
  _id: ID
  title: String!
  imageUrl: String!
  description: String!
  categories: [String]!
  createdDate: String
  likes: Int
  createdBy: User
  messages: [Message]
}

type User {
  _id: ID
  username: String! @unique
  password: String!
  email: String!
  joinDate: String
  avatar: String
  favorites: [Product]
}

type Message {
  _id: ID
  messageBody: String!
  messageUser: User!
  messageDate: String
}

type Token {
  token: String!
}

type ProductsPage {
  products: [Product]
  hasMore: Boolean!
}

type Query {
  getCurrentUser: User

  getProduct(_id: ID!): Product!
  getProducts(size: Int): [Product]!
  searchProducts(searchTerm: String): [Product]

  productsPage(page: Int!, size: Int!): ProductsPage
}

type Mutation {
  addProduct(
    title: String!
    imageUrl: String!
    description: String!
    categories: [String]!
    # takes a creatorId and returns 'createdBy' populated with User
    creatorId: String!
  ): Product!
  addProductMessage(messageBody: String!, userId: String!, productId: String!): Product!

  likeProduct(_id: ID, username: String): Product
  unlikeProduct(_id: ID, username: String): Product

  signinUser(username: String!, password: String!): Token
  signupUser(username: String!, email: String!, password: String!): Token
}
